
//render
### test render endpoint
GET https://adamu341test.onrender.com

//render
### test render endpoint
GET https://adamu341test.onrender.com/contacts


// localhost
### test local host endpoint
GET http://localhost:3000

// localhost
### test local host endpoint
GET http://localhost:3000/contacts 

// localhost
### test local host endpoint
GET http://localhost:3000/contacts/63ae52cb777e3b25663af5f0
